services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - OTEL_DENO=true
      - OTEL_SERVICE_NAME=api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
  lgtm:
    image: grafana/otel-lgtm:0.8.1
    container_name: lgtm
    restart: always
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    environment:
      - GF_PATHS_DATA=/data/grafana
    volumes:
      - ./lgtm/grafana:/data/grafana
      - ./lgtm/prometheus:/data/prometheus
      - ./lgtm/loki:/data/loki